[project]
name = "mp_emgdiaphragm"
version = "0.1.0"
description = "Code to replicate figures for the methods paper on fine-wire diaphragm emg"
license = "MIT"
readme = "README.md"
authors = [
    { name = "Jesús Peñaloza", email = "jesus.penalozaa@ufl.edu" },
    { name = "Taylor Holmes", email = "taylor.holmes@marquette.edu" }
]
requires-python = " >=3.9, <3.10"
dependencies = [
    "ipympl>=0.9.7",
    "matplotlib>=3.9.4",
    "mpl-interactions[jupyter]>=0.24.2",
    "neo==0.12.0",
    "numpy==1.26",
    "pyarrow>=19.0.1",
    "ruptures>=1.1.9",
    "scikit-learn>=1.6.1",
    "scipy>=1.13.1",
    "sonpy>=1.9.5",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel",
    "ruff",
]
